CREATE TABLE transformer (id INT8 GENERATED BY DEFAULT AS IDENTITY, courage INT4 CHECK (courage<=10 AND courage>=1), endurance INT4 CHECK (endurance<=10 AND endurance>=1), firepower INT4 CHECK (firepower<=10 AND firepower>=1), intelligence INT4 CHECK (intelligence<=10 AND intelligence>=1), name VARCHAR(255) NOT NULL, rank INT4 CHECK (rank<=10 AND rank>=1), skill INT4 CHECK (skill<=10 AND skill>=1), speed INT4 CHECK (speed<=10 AND speed>=1), strength INT4 CHECK (strength<=10 AND strength>=1), team VARCHAR(255), PRIMARY KEY (id));
ALTER TABLE IF EXISTS transformer ADD CONSTRAINT UK_pxvbog15uyvka6vtnyverx6ik UNIQUE (name);

INSERT INTO transformer (id, name, team, strength, intelligence, speed, endurance, rank, courage, firepower, skill) VALUES (1, 'Optimus Prime', 'AUTOBOT', 10, 9, 8, 7, 6, 5, 4, 3);
INSERT INTO transformer (id, name, team, strength, intelligence, speed, endurance, rank, courage, firepower, skill) VALUES (2, 'Bumblebee', 'AUTOBOT', 9, 8, 7, 6, 5, 4, 3, 2);
INSERT INTO transformer (id, name, team, strength, intelligence, speed, endurance, rank, courage, firepower, skill) VALUES (3, 'Bluestreak', 'AUTOBOT', 6, 6, 7, 9, 5, 2, 9, 7);
INSERT INTO transformer (id, name, team, strength, intelligence, speed, endurance, rank, courage, firepower, skill) VALUES (4, 'Hubcap', 'AUTOBOT', 4, 4, 4, 4, 4, 4, 4, 4);
INSERT INTO transformer (id, name, team, strength, intelligence, speed, endurance, rank, courage, firepower, skill) VALUES (5, 'Predaking', 'DECEPTICON', 10, 9, 8, 7, 6, 5, 4, 3);
INSERT INTO transformer (id, name, team, strength, intelligence, speed, endurance, rank, courage, firepower, skill) VALUES (6, 'Soundwave', 'DECEPTICON', 8, 9, 2, 6, 7, 5, 6, 10);
INSERT INTO transformer (id, name, team, strength, intelligence, speed, endurance, rank, courage, firepower, skill) VALUES (7, 'Shockwave', 'DECEPTICON', 8, 7, 6, 5, 4, 3, 2, 1);
INSERT INTO transformer (id, name, team, strength, intelligence, speed, endurance, rank, courage, firepower, skill) VALUES (8, 'Arcee', 'AUTOBOT', 6, 5, 4, 3, 2, 1, 1, 1);
